version: "3.9"
services:
  backend:
    image: documentcloud/sidekick_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/code/data
  frontend:
    image: node:12
    volumes:
      - ./frontend/node_modules:/app/node_modules
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
