language: rust
rust    : stable

addons:
  firefox: latest

install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - rustup component add clippy

script:
  - cargo clippy
  - cargo test
  - wasm-pack test --firefox --headless

